name: Docker Image CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag "solccp:$GITHUB_SHA"
      - name: Run the tests
        run: docker run "solccp:$GITHUB_SHA" /build/tests
