name: Run clang-format Linter

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: DoozyX/clang-format-lint-action@v0.13
        with:
          source: "."
          clangFormatVersion: 13
          inplace: True
          recursive: True
      - uses: EndBug/add-and-commit@v4
        with:
          author_name: clang-format
          author_email: style@github.actions
          message: "style fixup"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
